---
language: node_js
node_js:
- '0.10'
jdk:
- oraclejdk7
before_script:
- npm install -g grunt-cli
before_install:
- wget dist.neo4j.org/neo4j-community-2.1.7-unix.tar.gz
- tar -xzf neo4j-community-2.1.7-unix.tar.gz
- neo4j-community-2.1.7/bin/neo4j start
addons:
  sauce_connect: true
before_deploy:
- neo4j-community-2.1.7/bin/neo4j stop
- rm -rf neo4j-community-2.1.7 neo4j-community-2.1.7-unix.tar.gz
deploy:
  provider: heroku
  app: agilejs-team-1
  skip_cleanup: true
  api_key:
    secure: ! 'L4VmLgxkeor6UbSY9H1bVYppZVCDiliRYZnOuM722PtZbE7WrP5Vqy6p5sf0

      6h3vsNOl1+4JvY7ng/jSK+7Bmn/8VgN0YEzpXpyxpHJVkn2FcbZc/ugmaZdN

      DQ4TexBKifpv1sWOqZNYjvlGmR7neffzPNL1Xo85hOp9zS8kzmM='
env:
  global:
  - secure: ! 'MyTioo6Sn75VTWxNWTF7QzYe1Du9+f5cG9vPig8xsPP/izB0Z5ilCLZ00wYe

      CTM185BDKdBf0mhzO7lQUUuUfmOo0x2ehP4rqTS+Yk5kGgWZYX0bNVSOz5mT

      TEGFPSxaxHz/fFuPudIn1H1zBsUHgRW740B37upT9vnoJXNMjzc='
  - secure: ! 'paP9VW9Sa2wDoFrmUiHmDAZTBggOI2Y/QZhDn71vkT8H6GjhLO5xRIbGf3kR

      G5tNcKHB+YlJ8JL0azCI8vKOMQL695/iRKSOfcOo6v0wp2TyLEo0MPo3RAZz

      KvjOGVFP38akepnmJ0lF6gUlZZ00uHdpde7vk1tlgJiLesnvlHc='
